<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jsx</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>Javascript (React)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;)([a-zA-Z0-9:]++)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;(&lt;)/)(\2)(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.scope.between-tag-pair.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.any.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)((?i:body|head|html)\b)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.structure.any.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>name</key>
			<string>meta.tag.structure.any.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)((?i:address|blockquote|dd|div|section|article|aside|header|footer|nav|menu|dl|dt|fieldset|form|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|hr|pre)\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.block.any.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.block.any.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)((?i:a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var)\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.inline.any.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>((?: ?/)?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.inline.any.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)([a-zA-Z0-9:]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.other.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.other.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#entities</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;&gt;</string>
			<key>name</key>
			<string>invalid.illegal.incomplete.html</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>jsx-attribute</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;==)\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.embedded.line.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>jsx-comment-block</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.js</string>
		</dict>
		<key>jsx-comment-line</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=//)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.js</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-slash.js</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tag-generic-attribute</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=[^=])\b([a-zA-Z0-9:-]+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jsx-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jsx-comment-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jsx-comment-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unquoted-attribute</string>
				</dict>
			</array>
		</dict>
		<key>unquoted-attribute</key>
		<dict>
			<key>match</key>
			<string>(?&lt;==)(?:[^\s&lt;&gt;/'"]|/(?!&gt;))+</string>
			<key>name</key>
			<string>string.unquoted.html</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.react</string>
	<key>uuid</key>
	<string>5BF72E3C-8DC1-4B55-B232-CC821203C88D</string>
</dict>
</plist>
