<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>injectionSelector</key>
	<string>L:(source.js - comment.* - string.*)</string>
	<key>name</key>
	<string>Javascript (JSX)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;)([a-zA-Z0-9:]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.jsx</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=/(&gt;))|((&lt;)/)(\2)(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.block.jsx</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag-content.jsx</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G</string>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.block.jsx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?!\G)</string>
					<key>end</key>
					<string>(?!\G)(?=&lt;/)</string>
					<key>name</key>
					<string>meta.tag-content.jsx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#jsx-embedded-js</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.html.basic#entities</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;&gt;</string>
			<key>name</key>
			<string>invalid.illegal.incomplete.html</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>jsx-attribute</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;==)\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.embedded.line.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>jsx-comment-block</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.js</string>
		</dict>
		<key>jsx-comment-line</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=//)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.js</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-slash.js</string>
				</dict>
			</array>
		</dict>
		<key>jsx-embedded-js</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic#tag-generic-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jsx-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jsx-comment-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jsx-comment-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic#unquoted-attribute</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>uuid</key>
	<string>5BF72E3C-8DC1-4B55-B232-CC821203C88D</string>
</dict>
</plist>
